disabled_rules: # rule identifiers to exclude from running
    - line_length
    - trailing_newline
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - UtilityProject/AppLanguageChange
  
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
force_unwrapping: warning # implicitly

    